// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CurrencyRepository is an autogenerated mock type for the CurrencyRepository type
type CurrencyRepository struct {
	mock.Mock
}

// ConvertToUSD provides a mock function with given fields: currencies
func (_m *CurrencyRepository) ConvertToUSD(currencies []string) (map[string]float32, error) {
	ret := _m.Called(currencies)

	var r0 map[string]float32
	if rf, ok := ret.Get(0).(func([]string) map[string]float32); ok {
		r0 = rf(currencies)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float32)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(currencies)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
